name: Bug Report
description: File a bug report to help us improve UseKuro
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐱

        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: UseKuro Version
      description: What version of UseKuro are you running?
      placeholder: "v1.1.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: protocol
    attributes:
      label: Protocol
      description: Which protocol is affected?
      options:
        - HTTP
        - TCP
        - WebSocket
        - SFTP
        - Multiple protocols
        - Not protocol-specific
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug in detail. What did you expect to happen vs what actually happened?
      placeholder: |
        Example: When I run `usekuro run my-mock.kuro`, the server starts but returns 500 errors for all requests. I expected it to return the configured responses.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Create a .kuro file with...
        2. Run `usekuro run example.kuro`
        3. Send a request to...
        4. See error...
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: mock-file
    attributes:
      label: Mock Configuration (.kuro file)
      description: Please paste your .kuro file content that reproduces the issue
      render: yaml
      placeholder: |
        protocol: http
        port: 8080
        # ... rest of your mock configuration
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste relevant log output (run with LOG_LEVEL=debug for more details)
      render: shell
      placeholder: |
        INFO[2024-01-15 10:30:00] Mock loaded successfully...
        ERROR[2024-01-15 10:30:01] Failed to render template...
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: The mock should respond with status 200 and the configured body
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here:
        - Environment details (Docker, Kubernetes, etc.)
        - Network configuration
        - Related issues or discussions
        - Screenshots if applicable
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify you've completed these steps
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested with the latest version of UseKuro
          required: true
        - label: I have included sufficient information to reproduce the issue
          required: true
        - label: I have provided logs with LOG_LEVEL=debug if relevant
          required: false

  - type: markdown
    attributes:
      value: |
        ---

        **Thank you for helping improve UseKuro!** 🐱

        Our team will review your bug report and respond as soon as possible.

        For urgent issues, you can also reach out on our [Discord](https://discord.gg/usekuro).
